### PR TITLE
Dabekeh footer

### PR DESCRIPTION
**Pull request by remerdy1**
## Issues
  > Created 2 branches by mistake 
  
## Checklist
  - [x] My code follows the style of the project.
  - [x] My code has been self reviewed before to ensure that it is working, or will not cause issues with existing code.
  - [x] My code has appropriate comments for documentation.

### CODE REVIEW

**Comment by Winteeerrr** [comment]
Shouldn't `style.css` be renamed to something else?
Also, although it's not really important, maybe throw in a few comments for the css pages.

**Review by Winteeerrr — CHANGES_REQUESTED** [review]
Add comments to css pages (like the others)

**Comment by remerdy1** [comment]
> Shouldn't `style.css` be renamed to something else? Also, although it's not really important, maybe throw in a few comments for the css pages.

That's the file for generic components across pages so I thought it made the most sense

**Comment by Winteeerrr** [comment]
> > Shouldn't `style.css` be renamed to something else? Also, although it's not really important, maybe throw in a few comments for the css pages.
> 
> That's the file for generic components across pages so I thought it made the most sense

Fair enough. I think you're good to merge then.

**Review by HybridNinja — APPROVED** [review]

**Pull request merged**
