### PR TITLE
Merging account branch with the main branch

### PR DESCRIPTION
**Pull request by HybridNinja**
## Description
 - Added in an Accounts page and Change password page
  - Added in a JavaScript file for the change password
  - Created a CSS stylesheet for both pages

  
## Checklist
  - [ ] My code follows the style of the project.
  - [ ] My code has been self reviewed before to ensure that it is working, or will not cause issues with existing code.
  - [ ] My code has appropriate comments for documentation.

### CODE REVIEW

**Review by remerdy1 — CHANGES_REQUESTED** [review]
- Script tag for account.js should be added to the bottom of the body and not the head. 
- Possibly don't need 2 versions of bootstrap? (try deleting 4.0.0 and seeing if everything looks ok) 
- Add navbar to changepass.ejs

**Comment by HybridNinja** [comment]
Node isn't working for me right now it was yesterday but now it is saying error,  that the app crashed and is waiting for file changes so, do u know any solution to this problem because I made the changes i just want to test them out.

**Comment by Winteeerrr** [comment]
> Node isn't working for me right now it was yesterday but now it is saying error, that the app crashed and is waiting for file changes so, do u know any solution to this problem because I made the changes i just want to test them out.

Are you still having this problem? If so, what error are you receiving?

**Comment by HybridNinja** [comment]
> > Node isn't working for me right now it was yesterday but now it is saying error, that the app crashed and is waiting for file changes so, do u know any solution to this problem because I made the changes i just want to test them out.
> 
> Are you still having this problem? If so, what error are you receiving?

yeah still having it. it says Error: cannot find module
'cookie-parser'  up top with other stuff then it says require stack and it says app crashed - waiting for file changes before starting.

**Comment by Winteeerrr** [comment]
> > > Node isn't working for me right now it was yesterday but now it is saying error, that the app crashed and is waiting for file changes so, do u know any solution to this problem because I made the changes i just want to test them out.
> > 
> > 
> > Are you still having this problem? If so, what error are you receiving?
> 
> yeah still having it. it says Error: cannot find module 'cookie-parser' up top with other stuff then it says require stack and it says app crashed - waiting for file changes before starting.

Try `npm install cookie-parser -g`

**Comment by HybridNinja** [comment]
> > > > Node isn't working for me right now it was yesterday but now it is saying error, that the app crashed and is waiting for file changes so, do u know any solution to this problem because I made the changes i just want to test them out.
> > > 
> > > 
> > > Are you still having this problem? If so, what error are you receiving?
> > 
> > 
> > yeah still having it. it says Error: cannot find module 'cookie-parser' up top with other stuff then it says require stack and it says app crashed - waiting for file changes before starting.
> 
> Try `npm install cookie-parser -g`

its sorted now, I did have to do the npm install. That's all my issue was. Thank you very much though

**Review by remerdy1 — APPROVED** [review]

**Pull request merged**
